-- Guild Quest shared quest board (no auth prototype)
create table if not exists public.quests (
  id bigint generated by default as identity primary key,
  requester text not null,
  title text not null,
  level text not null,
  priority text not null,
  estimated_time text,
  description text,
  challenger text,
  successor1 text,
  successor2 text,
  status text not null default 'open',
  created_at timestamptz default now(),
  completed_at timestamptz
);

alter table public.quests enable row level security;

create policy "quests_select_anon"
  on public.quests for select
  to anon, authenticated
  using (true);

create policy "quests_insert_anon"
  on public.quests for insert
  to anon, authenticated
  with check (true);

create policy "quests_update_anon"
  on public.quests for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "quests_delete_anon"
  on public.quests for delete
  to anon, authenticated
  using (true);

alter publication supabase_realtime add table public.quests;
