-- Staff (party members) and quest activity logs

create table if not exists public.staff (
  id bigint generated by default as identity primary key,
  name text not null unique,
  role text not null,
  avatar text not null default '⚔️',
  hp int not null default 100 check (hp >= 0 and hp <= 100),
  mp int not null default 100 check (mp >= 0 and mp <= 100),
  status text not null default 'ready',
  sort_order int not null default 0,
  created_at timestamptz default now()
);

create table if not exists public.quest_logs (
  id bigint generated by default as identity primary key,
  quest_id bigint references public.quests (id) on delete set null,
  quest_title text not null,
  action text not null,
  actor_name text,
  details text,
  created_at timestamptz default now()
);

alter table public.staff enable row level security;
alter table public.quest_logs enable row level security;

create policy "staff_select_anon"
  on public.staff for select to anon, authenticated using (true);

create policy "staff_insert_anon"
  on public.staff for insert to anon, authenticated with check (true);

create policy "staff_update_anon"
  on public.staff for update to anon, authenticated using (true) with check (true);

create policy "staff_delete_anon"
  on public.staff for delete to anon, authenticated using (true);

create policy "quest_logs_select_anon"
  on public.quest_logs for select to anon, authenticated using (true);

create policy "quest_logs_insert_anon"
  on public.quest_logs for insert to anon, authenticated with check (true);

-- Seed default guild staff (skip if already seeded)
insert into public.staff (name, role, avatar, hp, mp, status, sort_order)
values
  ('佐藤', '早番リーダー', '⚔️', 84, 72, 'ready', 1),
  ('鈴木', 'カウンター担当', '📜', 92, 80, 'ready', 2),
  ('田中', 'フロア担当', '🛡️', 68, 90, 'busy', 3),
  ('高橋', '景品・POP担当', '✨', 100, 65, 'ready', 4),
  ('伊藤', '遅番サポート', '🎵', 76, 55, 'resting', 5)
on conflict (name) do nothing;

alter publication supabase_realtime add table public.quest_logs;
