-- Expeditions idle-game loop.
-- Safe additive migration for existing Guild Quest projects.

create table if not exists public.player_resources (
  id bigint generated by default as identity primary key,
  player_name text not null unique,
  expedition_tickets int not null default 0 check (expedition_tickets >= 0),
  gold int not null default 0 check (gold >= 0),
  items jsonb not null default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.expeditions (
  id bigint generated by default as identity primary key,
  player_name text not null,
  expedition_key text not null,
  expedition_name text not null,
  status text not null default 'in_progress' check (status in ('in_progress', 'completed', 'claimed')),
  started_at timestamptz not null default now(),
  ends_at timestamptz not null,
  claimed_at timestamptz,
  reward_exp int not null default 0,
  reward_gold int not null default 0,
  reward_guild_exp int not null default 0,
  reward_items jsonb not null default '{}'::jsonb,
  created_at timestamptz default now()
);

create index if not exists expeditions_player_status_idx
  on public.expeditions (player_name, status, ends_at desc);

create index if not exists expeditions_player_created_idx
  on public.expeditions (player_name, created_at desc);

alter table public.player_resources enable row level security;
alter table public.expeditions enable row level security;

create policy "player_resources_select_anon"
  on public.player_resources for select to anon, authenticated using (true);

create policy "player_resources_insert_anon"
  on public.player_resources for insert to anon, authenticated with check (true);

create policy "player_resources_update_anon"
  on public.player_resources for update to anon, authenticated using (true) with check (true);

create policy "expeditions_select_anon"
  on public.expeditions for select to anon, authenticated using (true);

create policy "expeditions_insert_anon"
  on public.expeditions for insert to anon, authenticated with check (true);

create policy "expeditions_update_anon"
  on public.expeditions for update to anon, authenticated using (true) with check (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'player_resources'
  ) then
    alter publication supabase_realtime add table public.player_resources;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'expeditions'
  ) then
    alter publication supabase_realtime add table public.expeditions;
  end if;
end $$;
