-- Guild calendar events and quest-event linking.
-- Numbered after existing expedition migration to avoid filename collisions.

create table if not exists public.calendar_events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  event_date date not null,
  start_time time,
  end_time time,
  event_type text not null default 'guild'
    check (event_type in ('guild', 'personal', 'shift', 'deadline', 'memo')),
  importance int not null default 3 check (importance >= 1 and importance <= 5),
  owner_name text,
  created_by text,
  linked_quest_id bigint references public.quests(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.quests
  add column if not exists linked_event_id bigint references public.calendar_events(id) on delete set null;

create index if not exists calendar_events_date_idx
  on public.calendar_events (event_date, start_time);

create index if not exists calendar_events_owner_idx
  on public.calendar_events (owner_name, event_date);

create index if not exists quests_linked_event_idx
  on public.quests (linked_event_id);

alter table public.calendar_events enable row level security;

create policy "calendar_events_select_anon"
  on public.calendar_events for select to anon, authenticated using (true);

create policy "calendar_events_insert_anon"
  on public.calendar_events for insert to anon, authenticated with check (true);

create policy "calendar_events_update_anon"
  on public.calendar_events for update to anon, authenticated using (true) with check (true);

create policy "calendar_events_delete_anon"
  on public.calendar_events for delete to anon, authenticated using (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'calendar_events'
  ) then
    alter publication supabase_realtime add table public.calendar_events;
  end if;
end $$;
