-- Adventurer notebook tasks.
-- Quests are now generated from personal tasks instead of being created directly.

create table if not exists public.adventurer_tasks (
  id bigint generated by default as identity primary key,
  owner_name text not null,
  title text not null,
  description text,
  status text not null default 'todo'
    check (status in ('todo', 'in_progress', 'completed', 'delegated')),
  priority int not null default 3 check (priority >= 1 and priority <= 5),
  importance int not null default 3 check (importance >= 1 and importance <= 5),
  due_date date,
  calendar_event_id bigint references public.calendar_events(id) on delete set null,
  is_public boolean not null default false,
  quest_id bigint unique references public.quests(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists adventurer_tasks_owner_idx
  on public.adventurer_tasks (owner_name, status, due_date);

create index if not exists adventurer_tasks_due_date_idx
  on public.adventurer_tasks (due_date);

create index if not exists adventurer_tasks_calendar_event_idx
  on public.adventurer_tasks (calendar_event_id);

create index if not exists adventurer_tasks_quest_idx
  on public.adventurer_tasks (quest_id);

alter table public.adventurer_tasks enable row level security;

create policy "adventurer_tasks_select_anon"
  on public.adventurer_tasks for select to anon, authenticated using (true);

create policy "adventurer_tasks_insert_anon"
  on public.adventurer_tasks for insert to anon, authenticated with check (true);

create policy "adventurer_tasks_update_anon"
  on public.adventurer_tasks for update to anon, authenticated using (true) with check (true);

create policy "adventurer_tasks_delete_anon"
  on public.adventurer_tasks for delete to anon, authenticated using (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'adventurer_tasks'
  ) then
    alter publication supabase_realtime add table public.adventurer_tasks;
  end if;
end $$;
