-- Guild operation notices, suggestions, assignments, and directives.

alter table public.staff
  add column if not exists role_level text not null default 'adventurer'
    check (role_level in ('adventurer', 'sub_master', 'guild_master'));

create table if not exists public.guild_notices (
  id bigint generated by default as identity primary key,
  type text not null
    check (type in ('deadline_warning', 'overdue', 'missing_task', 'suggestion', 'system')),
  title text not null,
  message text not null,
  target_player text,
  related_task_id bigint references public.adventurer_tasks(id) on delete set null,
  related_quest_id bigint references public.quests(id) on delete set null,
  created_at timestamptz default now(),
  dismissed boolean not null default false
);

create table if not exists public.guild_requests (
  id bigint generated by default as identity primary key,
  request_type text not null
    check (request_type in ('suggestion', 'assignment', 'directive')),
  from_player text,
  to_player text,
  task_title text not null,
  task_description text,
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'rejected', 'completed')),
  priority int not null default 3 check (priority >= 1 and priority <= 5),
  importance int not null default 3 check (importance >= 1 and importance <= 5),
  due_date date,
  calendar_event_id bigint references public.calendar_events(id) on delete set null,
  related_task_id bigint references public.adventurer_tasks(id) on delete set null,
  created_at timestamptz default now(),
  responded_at timestamptz
);

create index if not exists guild_notices_target_idx
  on public.guild_notices (target_player, dismissed, created_at desc);

create index if not exists guild_notices_task_type_idx
  on public.guild_notices (type, related_task_id)
  where dismissed = false;

create index if not exists guild_requests_to_player_idx
  on public.guild_requests (to_player, status, created_at desc);

create index if not exists guild_requests_from_player_idx
  on public.guild_requests (from_player, status, created_at desc);

alter table public.guild_notices enable row level security;
alter table public.guild_requests enable row level security;

create policy "guild_notices_select_anon"
  on public.guild_notices for select to anon, authenticated using (true);

create policy "guild_notices_insert_anon"
  on public.guild_notices for insert to anon, authenticated with check (true);

create policy "guild_notices_update_anon"
  on public.guild_notices for update to anon, authenticated using (true) with check (true);

create policy "guild_notices_delete_anon"
  on public.guild_notices for delete to anon, authenticated using (true);

create policy "guild_requests_select_anon"
  on public.guild_requests for select to anon, authenticated using (true);

create policy "guild_requests_insert_anon"
  on public.guild_requests for insert to anon, authenticated with check (true);

create policy "guild_requests_update_anon"
  on public.guild_requests for update to anon, authenticated using (true) with check (true);

create policy "guild_requests_delete_anon"
  on public.guild_requests for delete to anon, authenticated using (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'guild_notices'
  ) then
    alter publication supabase_realtime add table public.guild_notices;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'guild_requests'
  ) then
    alter publication supabase_realtime add table public.guild_requests;
  end if;
end $$;
